name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Download and install Gradle
        run: |
          GRADLE_VERSION=8.7
          GRADLE_ZIP=gradle-${GRADLE_VERSION}-bin.zip
          wget -q https://services.gradle.org/distributions/${GRADLE_ZIP}
          unzip -q ${GRADLE_ZIP} -d /usr/local/
          rm ${GRADLE_ZIP}
          export PATH="/usr/local/gradle-${GRADLE_VERSION}/bin:$PATH"
          gradle --version # Verifique se o Gradle foi instalado corretamente

      - name: Build with Gradle
        run: gradle assembleDebug # Observe que agora é 'gradle' e não './gradlew'

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: camera-app-apk
          path: app/build/outputs/apk/debug/app-debug.apk
