name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Ensure gradlew is executable and wrapper JAR is present
        run: |
          chmod +x gradlew
          mkdir -p gradle/wrapper
          # Se o gradle-wrapper.jar não existir ou for muito pequeno (vazio), baixe-o.
          if [ ! -f gradle/wrapper/gradle-wrapper.jar ] || [ ! -s gradle/wrapper/gradle-wrapper.jar ]; then
            echo "Downloading gradle-wrapper.jar..."
            wget -q https://services.gradle.org/distributions/gradle-8.7-bin.zip -O gradle-8.7-bin.zip
            unzip -o -q gradle-8.7-bin.zip
            mv gradle-8.7/lib/gradle-wrapper.jar gradle/wrapper/gradle-wrapper.jar
            rm -rf gradle-8.7 gradle-8.7-bin.zip
          fi
          ls -l gradle/wrapper/gradle-wrapper.jar # Verificar o tamanho do JAR
          java -jar gradle/wrapper/gradle-wrapper.jar --version # Tentar executar diretamente para testar

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: camera-app-apk
          path: app/build/outputs/apk/debug/app-debug.apk
