name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Validate gradlew permissions
        run: |
          chmod +x gradlew
          ls -l gradlew # Adiciona um log para verificar as permissões

      - name: Download Gradle Wrapper JAR if missing
        run: |
          mkdir -p gradle/wrapper
          if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "gradle-wrapper.jar not found, downloading..."
            wget -q https://services.gradle.org/distributions/gradle-8.7-bin.zip -O gradle-8.7-bin.zip
            unzip -q gradle-8.7-bin.zip
            mv gradle-8.7/lib/gradle-wrapper.jar gradle/wrapper/gradle-wrapper.jar
            rm -rf gradle-8.7 gradle-8.7-bin.zip
          else
            echo "gradle-wrapper.jar found."
          fi
          ls -l gradle/wrapper/gradle-wrapper.jar # Adiciona um log para verificar o JAR

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: camera-app-apk
          path: app/build/outputs/apk/debug/app-debug.apk
